web/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import SignupView

app_name = 'accounts'

urlpatterns = [
  path('login/', LoginView.as_view(), name='login'), #ログイン処理
  path('logout/', LogoutView.as_view(), name='logout'), #ログアウト処理
  path('signup/', SignupView.as_view(), name='signup'), #サインアップ処理
]

web/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.url')),
    path('accounts/', include('accounts.urls')), #ログイン機能を実装
    path('', include('main.urls')), #ページ
]

web/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('page1/', views.LoginPageView.as_view(), name='page1'),
    path('page0/', views.TopPageView.as_view(), name='page0'),
    path('', views.TopPageView.as_view(), name='page00'),

]

web/vlog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

web/accounts/models.py
from django.db import models

# Create your models here.

web/main/models.py
from django.db import models

# Create your models here.

CATEGORY = (('Home', 'ホーム'), ('welcome', 'ようこそ'))

class Home(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    category = models.CharField(
        max_length=100,
        choices=CATEGORY   
    )

    #データベースのタイトルを表示する関数
    def __str__(self):
        return self.title

web/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


#サインアップに使用するフォームのクラスを作成。データベースはUserを使用
class SignupForm(UserCreationForm):
  
  class Meta:
    model = User
    fields = ('username',)

web/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView

# Create your views here.

from .forms import SignupForm

class SignupView(CreateView):
  models = User
  form_class = SignupForm
  template_name = 'accounts/signup.html'
  success_url = reverse_lazy('page1')

web/main/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import Home
# Create your models here.

class LoginPageView(ListView):
    template_name = 'pages/page1.html'
    model = Home

class TopPageView(ListView):
    template_name = 'pages/page0.html'
    model = Home
# Create your views here.

web/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}アカウント作成{% endblock title %}

{% block h1 %}アカウント作成{% endblock h1 %}

{% block content%}
<form method="POST" class="p-4 m-4 bg-primary border border-success rounded form-group">
  {% csrf_token %}
  <input type="text" name="username" class="form-control my-4" placeholder="ユーザー名">
  <input type="password" class="form-control mt-4" placeholder="パスワード" name="password1">
  <input type="password" class="form-control mt-4" placeholder="パスワード確認用" name="password2">
  <small class="mb-2 d-block text-start">パスワードは8文字以上で設定してください</small>
  {% if form.errors %}
  <span class="mb-2 small text-danger d-block text-start">利用できないユーザーIDまたはパスワードです</span>
  {% endif %}
  <button type="submit" class="btn btn-success m-2">サインアップ</button>
</form>
{% endblock %}

web/main/templates/pages/page0.html
{% extends 'base.html' %}

{% block title %}
ページトップ
{% endblock %}

{% block h1 %}
ページトップ
{% endblock h1 %}

web/main/templates/pages/page1.html
{% extends 'base.html' %}

{% block title %}遷移ページ{% endblock %}
{% block h1 %}ようこそ{% endblock h1 %}
{% block content02 %}
<input type="text" name="text1">
{% endblock content02 %}

web/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- bootstrap css -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>{% block title %}{% endblock title %} | TEST</title>
</head>
<body>
<div class="navbar-nav d-flex flex-row">
  {% if request.user.is_authenticated %}
    <a class="vav-link mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
  {% else %}
    <a class="nav-link mx-3" href="{% url 'accounts:login' %}">ログイン</a>
    <a class="nav-link mx-3" href="{% url 'accounts:signup' %}">サインアップ</a>
  {% endif %}
</div>

  <div class="position-absolute top-0 start-50 translate-middle-x p-4 text-info bg-primary">
    <h1>{% block h1 %}{% endblock h1 %}</h1>
    {% block content %}{% endblock content %}
  </div>
  <div class="position-absolute top-50 start-50 translate-middle bg-success">
    {% block content02 %}{% endblock content02 %}
  </div>
</body>
</html>